### ISSUE TITLE
Crash on CentOS 7.6 x64

### ISSUE THREAD

**Issue by lipingruan** [Brooooooklyn/pinyin#100]
```
TypeError: Can not find node binding files from @napi-rs/pinyin-linux-x64-gnu, @napi-rs/pinyin-linux-x64-gnux32, @napi-rs/pinyin-linux-x64-musl and __project/node_modules/@napi-rs/pinyin/pinyin.linux-x64-gnu.node, __project/node_modules/@napi-rs/pinyin/pinyin.linux-x64-gnux32.node, __project/node_modules/@napi-rs/pinyin/pinyin.linux-x64-musl.node
    at loadBinding (/home/admin/celve_node/node_modules/@node-rs/helper/lib/loader.js:27:11)
    at Object.<anonymous> (/home/admin/celve_node/node_modules/@napi-rs/pinyin/index.js:11:18)

```

**Comment by Brooooooklyn** [comment]
Same with https://github.com/swc-project/swc/issues/1410 .
Support CentOS7 is out of scope. I can just guarantee to compatible with the Node.js official docker images.
